### ISSUE TITLE
Blinking

### ISSUE THREAD

**Issue by P9Q** [superevilmegaco/Hide-Most-Visited-Pages-Reloaded#11]
I added the following style, but when I open a new tab it's first white then turns black, It's kind of annoying, is there any solution?

```CSS
body {
    background-color: #1f1f1f;
}

**Comment by jnavb** [comment]
same here, did you solve it?

**Comment by jnavb** [comment]
Yes, that would be nice although in my case Im using #2d2d2d.

I still don´t understand why the iframe couldn´t load the custom css/js from a local path, is it possible?

**Comment by gorillamoe** [comment]
I might have found another workaround. Version 7.0.0 should hit the store soon.
The only catch with this workaround is, that it takes a second load of the newtab page to take effect.

That means:

1. You enter the initial load background color
2. Hit CTRL + S to save the background color
3 Open a new tab (blinking is still there)
4. Open another tab (blinking is gone; until you change the background color again)

I guess that is the best workaround I can imagine (with the restriction for chrome developers in place).

This is what the new options page looks like:

![image](https://user-images.githubusercontent.com/1384938/51446060-df057280-1d0c-11e9-9638-e8efb03e3847.png)

**Comment by gorillamoe** [comment]
I also have a workaround for

>  that it takes a second load of the newtab page to take effect

I'll fix that in the evening and roll-out should start around 21:00 GMT+0100.

**Comment by jnavb** [comment]
Nicely done! now is barely noticeable.

Is there some way to specify the color of the first load? Maybe you could choose between a preset of 4 different blacks for example (I think that is the most common use case)

**Comment by gorillamoe** [comment]
> Nicely done! now is barely noticeable.
> 
> Is there some way to specify the color of the first load? Maybe you could choose between a preset of 4 different blacks for example (I think that is the most common use case)

You should be able to set the initial background-color in the options page.
This should get loaded async and should be available immediately when you open up a new tab page.
It's a very ugly hack, but it's working :+1: 

See here, for a working example of no flashing, once it is saved: https://youtu.be/1aygd7aNUUA
